version: '3.9'

services:
  web:
    build: ./backend
    command: gunicorn "app.app:app" --bind 0.0.0.0:5000
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/resumes
      - CELERY_BROKER_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis

  worker:
    build: ./backend
    command: celery -A app.celery worker --loglevel=info
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/resumes
      - CELERY_BROKER_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis

  redis:
    image: redis:6

  db:
    image: postgres:14
    environment:
      - POSTGRES_DB=resumes
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: